version: "3"
services:
  web:
    image: ds/nginx
    hostname: web
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/ssl:/etc/ssl"
      - "./web:/var/www/html"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "4000:80"
    logging:
      driver: json-file
    networks:
      - webnet
  php:
    image: ds/php
    hostname: php
    tty: true
    stdin_open: true
    ports:
        - "9000:9000"
    volumes:
        - "./web:/var/www/html"
    logging:
      driver: json-file
    networks:
        - webnet
  mysqldb:
    image: ds/mysql
    hostname: mysqldb
    volumes:
      - "./web/db/mysql:/var/lib/mysql"
    ports:
      - "8989:3306"
    environment:
      - MYSQL_DATABASE=magento
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    logging:
      driver: json-file
    networks:
      - webnet
networks:
  webnet:
