FROM alpine:3.7

RUN apk add --no-cache php7 \
    php7-fpm \
    php7-cli
#
#COPY docker-php-entrypoint /usr/local/bin/
#
#ENTRYPOINT ["docker-php-entrypoint"]

#RUN service php7-fpm restart

WORKDIR /var/www

EXPOSE 9000

CMD ["php"]